name: Certora Verify
description: Checkout, install dependencies, and run Certora verification

inputs:
  contractFile:
    description: Contract config file for Certora verification
    required: true

runs:
  using: composite
  
  steps:
    - name: Install python
      uses: actions/setup-python@v2
      with: { python-version: 3.9 }

    - name: Install java
      uses: actions/setup-java@v1
      with: { java-version: "11", java-package: jre }

    - name: Install certora cli
      shell: bash
      run: pip3 install certora-cli==7.0.7

    - name: Install solc
      shell: bash
      run: |
        wget https://github.com/ethereum/solidity/releases/download/v0.8.24/solc-static-linux
        chmod +x solc-static-linux
        sudo mv solc-static-linux /usr/local/bin/solc8.24
   
    - name: Verify
      run: |
        sh certora/munge.sh
        certoraRun certora/conf/${{ inputs.contractFile }}
      env:
        CERTORAKEY: ${{ inputs.certoraKey }}
      shell: bash
